using System.Collections.Generic;
using System.Text;
using EasyValidate.Types;

namespace EasyValidate.Handlers
{
    internal class UsingImportsHandler : ValidationHandlerBase
    {
        public override (StringBuilder sb, Dictionary<string, List<string>> awaitableMembers) Next(HandlerParams @params)
        {
            var (nextsp, awaitableMembers) = base.Next(@params);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using global::System;");
            sb.AppendLine("using global::System.Collections.Generic;");
            sb.AppendLine("using global::EasyValidate.Core.Abstraction;");
            sb.AppendLine("using global::EasyValidate.Core.Attributes;");
            sb.Append(nextsp);
            sb.AppendLine("#nullable restore");
            return (sb, awaitableMembers);

        }
    }
}
